#!/bin/sh
#
# depmk - Like pkgmk but for dependencies
# onodera, https://github.com/onodera-punpun

# TODO: Add post-install support

## CONFIGURATION

# Config directory location
config="/etc/prt.conf"


## FUNCTIONS

# This function installs the dependencies
install() {
	for location in $installme; do
		# cd to Pkgfile location
		cd "/usr/ports/$location"

		# Install dependency
		pkgmk -d $options
		if [ "$?" -ge 1 ]; then
			exit 1
		fi
	done
}


## EXECUTE

for flag in "$@"; do
	case "$flag" in
		-h|--help)
			echo "Usage: depmk [options]"
			echo ""
			echo "options:"
			echo "  -i,   --install         build and install dependencies"
			echo "  -do,  --download-only   do not build, only download missing source file(s)"
			echo "  -if,  --ignore-fp       build dependencies without checking footprint"
			echo "  -in,  --ignore-new      build dependencies, ignore [NEW] footprint missmatches"
			echo "  -im,  --ignore-md       build dependencies without checking md5sum"
			echo "  -ns,  --no-strip        do not strip executable binaries or libraries"
			echo "  -v,   --version         print version and exit"
			echo "  -h,   --help            print help and exit"
			exit 0
			;;
		-v|--version)
			echo "depmk (prt-utils-extra) 0.7.4"
			exit 0
			;;
		-i|--install)
			options+=" -i"
			;;
		-do|--download-only)
			options+=" -do"
			;;
		-if|--ignore-fp)
			options+=" -if"
			;;
		-in|--ingore-new)
			options+=" -in"
			;;
		-im|--ingore-md5)
			options+=" -im"
			;;
		-ns|--no-strip)
			option+=" -ns"
			;;
		*)
			echo "depmk: invalid option $1"
			exit 1
			;;
	esac
done

installme="$(depls | tac)"

if [ -n "$installme" ]; then
	install
else
	echo "=======> INFO: No dependencies to install."
	exit 0
fi
