#!/bin/sh
#
# prtl - Prints port location
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Config location
config="/etc/prt.conf"

## FUNCTIONS

# This function gets some basic info
info() {
	order="$(grep "^order" "$config" | cut -d " " -f 2-)"
	alias="$(grep "^alias" "$config" | cut -d " " -f 2-)"

	ports="$(ports -l)"
	installed="$(pkginfo -i | cut -d " " -f 1)"
}

location() {
	location="$(ports -l | grep "/$@$")"

	# Order
	# TODO: Find a better way of doing this?
	if [ "$(echo "$location" | wc -l)" -ge 2 ]; then
		for line in $order; do
			locationorder="$(echo "$location" | grep "^$line/")"
			if [ -n "$locationorder" ]; then
				location="$locationorder"
				break
			fi
		done
	fi

	if [ -d "/usr/ports/$location" -a -n "$location" ]; then
		echo "/usr/ports/$location"
	else
		echo "prtl: invalid port $1"
		exit 1
	fi
}


## EXECUTE

if [ $# -eq 0 ]; then
	echo "prtl: please specify a port"
	exit 1
fi

for flag in "$@"; do
	case "$flag" in
		-h|--help)
			echo "Usage: prtl [options] [port]"
			echo ""
			echo "options:"
			echo "  -v,   --version         print version and exit"
			echo "  -h,   --help            print help and exit"
			exit 0
			;;
		-v|--version)
			echo "prtl (prt-utils-extra) 0.7.6"
			exit 0
			;;
		*)
			info
			location $@
			;;
	esac
done
